### PR TITLE
Added view for analyzing and classifying variants with IGV integration

### PR DESCRIPTION
**Pull request by mhkc**
This PR adds a view for analyzing and classifying variants called by TbProfiler and called SNV and SV variants.

This PR depends on this `bonsai-prp` PR, https://github.com/Clinical-Genomics-Lund/bonsai-prp/pull/33

## Changes

 - Added view for analyszing variants with filtering (/samples/<sample_id>/resistance/variants)
 - Added IGV genome browser integration to variant analysis view.
 - Bonsai support display of SV and SNV variants.
 - A user can classify variant as accepted or as rejected based and annotate why it was dissmissed.
 - A user can annotate that a variant yeilds resistance to additional anitbiotics
 - Placeholder Export to LIMBS button to the sidebar in the variants view

### How to setup and perform the tests

1. build a new container which includes the linked version of bonsai-prp
2. Make sure that you mount the following directories to the api container. Copy the contents of my directories (/data/bnf/dev/markus/bonsai_dev/volumes/api) to your folder.
```
      - "./volumes/api/reference_genomes:/tmp/reference_genomes"
      - "./volumes/api/annotations:/tmp/annotations"
      - "./volumes/api/sample_data:/tmp/samples"
```
4. load the attached test sample to Bonsai

### Expected outcome 

- Filtering variants should work
- Classifying variant should work
- Annotating additional resistance should work
- IGV integration should work

A short description of the expected outcome of the test above.

### Additional context
[test_mtuberculosis_1.json](https://github.com/Clinical-Genomics-Lund/bonsai/files/14509329/test_mtuberculosis_1.json)

### CODE REVIEW

**Comment by LordRust** [comment]
(Commenting on function in the GUI, not the code. Some of the comments are nice-to-haves and some are not yet implemented, so the comments are mix of needs, wants and bugs)
WebIGV
  - BUG: SV from delly do not show the correct coordinates when opening
  - NICE: the gff track does not show the names of the features without clicking on them
  - NEED: the bed regions with the analyzed areas from tbprofiler is missing
  - NICE: if possible show the amino acid part of the gff as in the regular IGV

Resistance prediction part
  - accepting/rejecting variant works very good
  - NICE: you can reject an antibiotic which has not been assigned to the mutations which is a bit wierd, when selecting reject, a filtered drop down would be nice
  - NEED: Isoniazid should be possible to assign as low and high resistance
  - NICE: hyperlinks on genes are broken
  - NICE: being able to sort table by absolute genomic position would be nice since you might get an idea of wither polymorphic sites are clustered in one or many of the targets in the bed file
  - NICE-NEED: adding a column with the predicted variant effect. If we do not have it already, VEP or similar would be good 
  - BUG: adding a number to filter on % or depth throws an type error
  - NICE: frequency and depth filter would be usable for both high- and low-cutoffs
  - NICE: the SV part has no guidance to the effect at all, if we at least get the AMR determining regions included that is at least a start

general things which I assume are just temporarily broken
  - export to lims is not implemented
  - quality control box is broken

**Comment by mhkc** [comment]
From 

> (Commenting on function in the GUI, not the code. Some of the comments are nice-to-haves and some are not yet implemented, so the comments are mix of needs, wants and bugs) WebIGV
> 
>     * BUG: SV from delly do not show the correct coordinates when opening
> 
>     * NICE: the gff track does not show the names of the features without clicking on them
> 
>     * NEED: the bed regions with the analyzed areas from tbprofiler is missing
> 
>     * NICE: if possible show the amino acid part of the gff as in the regular IGV
> 
> 
> Resistance prediction part
> 
>     * accepting/rejecting variant works very good
> 
>     * NICE: you can reject an antibiotic which has not been assigned to the mutations which is a bit wierd, when selecting reject, a filtered drop down would be nice
> 
>     * NEED: Isoniazid should be possible to assign as low and high resistance
> 
>     * NICE: hyperlinks on genes are broken
> 
>     * NICE: being able to sort table by absolute genomic position would be nice since you might get an idea of wither polymorphic sites are clustered in one or many of the targets in the bed file
> 
>     * NICE-NEED: adding a column with the predicted variant effect. If we do not have it already, VEP or similar would be good
> 
>     * BUG: adding a number to filter on % or depth throws an type error
> 
>     * NICE: frequency and depth filter would be usable for both high- and low-cutoffs
> 
>     * NICE: the SV part has no guidance to the effect at all, if we at least get the AMR determining regions included that is at least a start
> 
> 
> general things which I assume are just temporarily broken
> 
>     * export to lims is not implemented
> 
>     * quality control box is broken

WebIGV

 - [ ] BUG: SV from delly do not show the correct coordinates when opening
 - [ ] NICE: the gff track does not show the names of the features without clicking on them
 - [ ] NEED: the bed regions with the analyzed areas from tbprofiler is missing
 - [ ] NICE: if possible show the amino acid part of the gff as in the regular IGV

Resistance prediction part

 - [ ] NICE: you can reject an antibiotic which has not been assigned to the mutations which is a bit wierd, when selecting reject, a filtered drop down would be nice
 - [ ] NEED: Isoniazid should be possible to assign as low and high resistance
 - [ ] NICE: hyperlinks on genes are broken
 - [ ] NICE: being able to sort table by absolute genomic position would be nice since you might get an idea of wither polymorphic sites are clustered in one or many of the targets in the bed file
 - [ ] NICE-NEED: adding a column with the predicted variant effect. If we do not have it already, VEP or similar would be good
 - [ ] BUG: adding a number to filter on % or depth throws an type error
 - [ ] NICE: frequency and depth filter would be usable for both high- and low-cutoffs
 - [ ] NICE: the SV part has no guidance to the effect at all, if we at least get the AMR determining regions included that is at least a start

**Comment by LordRust** [comment]
Tested all the functionality in the GUI and the variant calling curation system is now good.

**Review by LordRust — APPROVED** [review]
Tested all functionality on the GUI side. The actual code has just been scanned through.

**Pull request merged**
